#!/bin/bash
cur_dir=`dirname $0`
#exec /usr/java/default/bin/java -jar $cur_dir/aibi*.jar $* 2>>$cur_dir/privacyprot.log
exec /usr/java/default/bin/java -jar $cur_dir/aibi*.jar "$1" "$2" 2>>$cur_dir/privacyprot.log
